/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_preferme_ipc_SharedMemery */

#ifndef _Included_com_github_preferme_ipc_SharedMemery
#define _Included_com_github_preferme_ipc_SharedMemery
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_preferme_ipc_SharedMemery
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_preferme_ipc_SharedMemery_initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_github_preferme_ipc_SharedMemery
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_preferme_ipc_SharedMemery_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_github_preferme_ipc_SharedMemery
 * Method:    writerIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_preferme_ipc_SharedMemery_writerIndex
  (JNIEnv *, jobject);

/*
 * Class:     com_github_preferme_ipc_SharedMemery
 * Method:    writableBytes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_preferme_ipc_SharedMemery_writableBytes
  (JNIEnv *, jobject);

/*
 * Class:     com_github_preferme_ipc_SharedMemery
 * Method:    readerIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_preferme_ipc_SharedMemery_readerIndex
  (JNIEnv *, jobject);

/*
 * Class:     com_github_preferme_ipc_SharedMemery
 * Method:    readableBytes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_preferme_ipc_SharedMemery_readableBytes
  (JNIEnv *, jobject);

/*
 * Class:     com_github_preferme_ipc_SharedMemery
 * Method:    getBytes
 * Signature: (I[BII)Lcom/github/preferme/ipc/SharedMemery;
 */
JNIEXPORT jobject JNICALL Java_com_github_preferme_ipc_SharedMemery_getBytes
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_github_preferme_ipc_SharedMemery
 * Method:    setBytes
 * Signature: (I[BII)Lcom/github/preferme/ipc/SharedMemery;
 */
JNIEXPORT jobject JNICALL Java_com_github_preferme_ipc_SharedMemery_setBytes
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_github_preferme_ipc_SharedMemery
 * Method:    readBytes
 * Signature: ([BII)Lcom/github/preferme/ipc/SharedMemery;
 */
JNIEXPORT jobject JNICALL Java_com_github_preferme_ipc_SharedMemery_readBytes
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_github_preferme_ipc_SharedMemery
 * Method:    writeBytes
 * Signature: ([BII)Lcom/github/preferme/ipc/SharedMemery;
 */
JNIEXPORT jobject JNICALL Java_com_github_preferme_ipc_SharedMemery_writeBytes
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
