/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_preferme_ipc_SharedMemery */

#ifndef _Included_com_github_preferme_ipc_SharedMemery
#define _Included_com_github_preferme_ipc_SharedMemery
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_preferme_ipc_SharedMemery
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_preferme_ipc_SharedMemery_initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_github_preferme_ipc_SharedMemery
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_preferme_ipc_SharedMemery_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_github_preferme_ipc_SharedMemery
 * Method:    writableBytes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_preferme_ipc_SharedMemery_writableBytes
  (JNIEnv *, jobject);

/*
 * Class:     com_github_preferme_ipc_SharedMemery
 * Method:    readableBytes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_preferme_ipc_SharedMemery_readableBytes
  (JNIEnv *, jobject);

/*
 * Class:     com_github_preferme_ipc_SharedMemery
 * Method:    read
 * Signature: (Lcom/github/preferme/ipc/ByteBufferFactory;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_github_preferme_ipc_SharedMemery_read
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_github_preferme_ipc_SharedMemery
 * Method:    write
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_github_preferme_ipc_SharedMemery_write
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
