/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

//#include "c.h"
#include <cassert>

int main() {
//    c::Greeter greeter;
//    assert(greeter.greeting().compare("Hello, World!") == 0);
    return 0;
}
